version: "3.5"
services:
  binance_test:
    container_name: binance_test
    image: binance_test
    build: "./"
    restart: unless-stopped
    command: "./binance"
    ports:
      - "8090:8090"
    depends_on:
      - postgres

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=artyom
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - /binance/postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql